runtime: go113
service: default
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80

handlers:
- url: /.*
  script: auto

vpc_access_connector:
  name: "projects/letustalk/locations/us-central1/connectors/letustalk-connect"

env_variables:
  PORT: 8080
  MYSQL_SOURCE: BambooTuna:pass@tcp(10.128.0.2:3306)/letustalk
  MYSQL_USER: BambooTuna
  MYSQL_PASS: pass
  MYSQL_HOST: 10.128.0.2
  MYSQL_PORT: 3306
  MYSQL_DATABASE: letustalk
