name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16.0]

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        cd front
        npm install
        npm run build
        cd ../
      env:
        NODE_ENV: development
        VUE_APP_SERVER_ENDPOINT: ${{ secrets.APIEndpoint }}
        VUE_APP_PAYMENT_PUB_KEY: ${{ secrets.PaymentPublicKey }}

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: GAE deploy
      run: |
        sudo apt-get install google-cloud-sdk-app-engine-go
        echo ${GCLOUD_SERVICE_KEY} | base64 -d > ./service_key.json
        echo 'github-actions@${PROJECT_NAME}.iam.gserviceaccount.com' | gcloud auth activate-service-account --key-file ./service_key.json
        gcloud app deploy app.yaml --project ${PROJECT_NAME}
      env:
        CI: true
        PROJECT_NAME: ${{ secrets.ProjectName }}
        GCLOUD_SERVICE_KEY: ${{ secrets.GcloudServiceKey }}
